version: '3.4'
services:
    react-app-container:
      stdin_open: true    
      container_name: react-app-container  
      image: ayan321/react-app
      # image: react-app
      # build:
      #   context: .
      #   dockerfile: Dockerfile
      expose:
        - 5000
      ports:
        - 5000:80
      environment:
          - CHOKIDAR_USEPOLLING=true
          # - REACT_APP_BACKEND_DOMAIN: http://localhost:9090/